### ISSUE TITLE
Plugin fails to load on Obsidian Android.

### ISSUE THREAD

**Issue by Con-Sdr** [iiiBird/obsidian-telegram-reminder#1]
I've extracted the telegram zip file into a folder which contains the manifest and main js files. That folder is the pasted into my plugins folder in my vault location.

The plugin shows up but it fails to load for some reason, am I doing something wrong?

Ps. I'm using a phone on android 11

![Screenshot_20230702-034722](https://github.com/iiiBird/obsidian-telegram-reminder/assets/118404032/baaa896d-721e-41b8-8aea-bbfe1cf5864b)
![Screenshot_20230702-033648](https://github.com/iiiBird/obsidian-telegram-reminder/assets/118404032/413c32d8-5918-4547-a81d-f935f5ed22bf)

**Comment by iiiBird** [comment]
Hello. Judging by the search results on Google, this seems to be a common issue with Obsidian itself. I will see what I can do on my end to fix it.

**Comment by iiiBird** [comment]
From what I've found - any node library can't be used on mobile devices. I use "node-telegram-bot-api" in my plugin. Unfortunately, there's no way to implement this. In the next release, I'll just set "isDesktopOnly: true" for the plugin.
