### ISSUE TITLE
Not working in iOS

### ISSUE THREAD

**Issue by HochuSirok** [iiiBird/obsidian-telegram-reminder#2]
![IMG_2754](https://github.com/iiiBird/obsidian-telegram-reminder/assets/137641387/db727648-918c-4171-8ecb-f6ec9a4d5eb7)

Does not work on iOS (16.5). Added files to the folder.

**Comment by seaorjan** [comment]
same problem

**Comment by iiiBird** [comment]
https://github.com/iiiBird/obsidian-telegram-reminder/issues/1#issuecomment-1914074959
